// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Util.DbContextService;

#nullable disable

namespace WeatherConsumer.Migrations
{
    [DbContext(typeof(SqlDataContext))]
    [Migration("20250815024803_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeatherApi.Models.Entities.CurrentWeather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("interval")
                        .HasColumnType("int");

                    b.Property<int>("is_day")
                        .HasColumnType("int");

                    b.Property<double>("temperature")
                        .HasColumnType("float");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weathercode")
                        .HasColumnType("int");

                    b.Property<int>("winddirection")
                        .HasColumnType("int");

                    b.Property<double>("windspeed")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("curretWeather");
                });

            modelBuilder.Entity("WeatherApi.Models.Entities.CurrentWeatherUnits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("interval")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("is_day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("temperature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weathercode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("winddirection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("windspeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("currentWeatherUnits");
                });

            modelBuilder.Entity("WeatherApi.Models.Entities.WeatherEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("current_weatherId")
                        .HasColumnType("int");

                    b.Property<int>("current_weather_unitsId")
                        .HasColumnType("int");

                    b.Property<double>("elevation")
                        .HasColumnType("float");

                    b.Property<double>("generationtime_ms")
                        .HasColumnType("float");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("timezone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("timezone_abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("utc_offset_seconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("current_weatherId");

                    b.HasIndex("current_weather_unitsId");

                    b.ToTable("weather");
                });

            modelBuilder.Entity("WeatherApi.Models.Entities.WeatherEntity", b =>
                {
                    b.HasOne("WeatherApi.Models.Entities.CurrentWeather", "current_weather")
                        .WithMany()
                        .HasForeignKey("current_weatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeatherApi.Models.Entities.CurrentWeatherUnits", "current_weather_units")
                        .WithMany()
                        .HasForeignKey("current_weather_unitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("current_weather");

                    b.Navigation("current_weather_units");
                });
#pragma warning restore 612, 618
        }
    }
}
